#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

# Add source files
env.add_source_files(env.modules_sources, "*.cpp")
env.add_source_files(env.modules_sources, "tests/*.cpp")
